# GitHub Actions Workflow: .github/workflows/ami-build.yml

name: Build AMI and Update Launch Template

on:
  push:
    branches:
      - main

jobs:
  build_ami:
    runs-on: ubuntu-latest
    env:
      LAUNCH_TEMPLATE_ID: lt-01e9ab7bca374ee10  # Variable for Launch Template ID

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      # Print Working Directory
      - name: Print Working Directory
        run: pwd

      # List Root Directory Files
      - name: List Root Directory Files
        run: ls -la

      # List Pipeline Directory Files
      - name: List Pipeline Directory Files
        run: ls -la pipeline

      # List Website Files
      - name: List Website Files
        run: ls -la pipeline/website-files

      # Display index.html Content
      - name: Display index.html Content
        run: cat pipeline/website-files/index.html

      # Set up Packer
      - name: Set up Packer
        uses: hashicorp/setup-packer@v2
        with:
          version: '1.11.2'

      # Verify Packer Version
      - name: Verify Packer Version
        run: packer version

      # Install AWS CLI and jq
      - name: Install AWS CLI and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli jq

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Get the latest AMI ID or use a default AMI
      - name: Get Latest AMI ID
        id: get_ami
        run: |
          LATEST_AMI=$(aws ec2 describe-images --owners self --filters "Name=name,Values=my-portfolio-ami-pipeline-image-*" --query "Images | sort_by(@, &CreationDate)[-1].ImageId" --output text)
          echo "LATEST_AMI=$LATEST_AMI"
          if [ -z "$LATEST_AMI" ] || [ "$LATEST_AMI" = "None" ] || [ "$LATEST_AMI" = "null" ]; then
            echo "No previous AMI found, using default AMI."
            LATEST_AMI="ami-057660df437592ff2"  # Replace with a valid default AMI ID
          fi
          echo "LATEST_AMI=$LATEST_AMI" >> $GITHUB_ENV

      # Initialize Packer
      - name: Initialize Packer
        run: |
          PACKER_LOG=1 packer init pipeline/packer-template.pkr.hcl

      # Validate Packer Template
      - name: Validate Packer Template
        run: |
          packer validate -var "source_ami=${{ env.LATEST_AMI }}" -var "template_dir=$PWD/pipeline" pipeline/packer-template.pkr.hcl

      # Build AMI with Packer
      - name: Build AMI with Packer
        id: build_ami
        env:
          PACKER_LOG: 1
        run: |
          packer build -force -machine-readable -var "source_ami=${{ env.LATEST_AMI }}" -var "template_dir=$PWD/pipeline" pipeline/packer-template.pkr.hcl | tee build.log
          AMI_ID=$(awk -F, '/artifact,0,id/ {print $6}' build.log | cut -d ':' -f2)
          echo "AMI_ID=$AMI_ID"
          echo "AMI_ID=$AMI_ID" >> $GITHUB_ENV

      # Update Launch Template with New AMI
      - name: Update Launch Template
        run: |
          aws ec2 create-launch-template-version \
            --launch-template-id ${{ env.LAUNCH_TEMPLATE_ID }} \
            --source-version '$Default' \
            --version-description "New version with AMI ${{ env.AMI_ID }}" \
            --launch-template-data "{\"ImageId\":\"${{ env.AMI_ID }}\"}"
          # Set this version as the default version
          aws ec2 modify-launch-template \
            --launch-template-id ${{ env.LAUNCH_TEMPLATE_ID }} \
            --default-version '$Latest'
