name: Build AMI on Push

on:
  push:
    branches:
      - main

jobs:
  build_ami:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Packer
      - name: Set up Packer
        uses: hashicorp/setup-packer@v2
        with:
          version: '1.11.2'  # Use the latest version or specify the version you need

      # Verify Packer Version
      - name: Verify Packer Version
        run: packer version

      # Install AWS CLI and jq
      - name: Install AWS CLI and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli jq

      # Set up AWS credentials using GitHub Secrets
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Get latest AMI ID or fallback to default AMI
      - name: Get Latest AMI ID
        id: get_ami
        run: |
          LATEST_AMI=$(aws ec2 describe-images --owners self --filters "Name=name,Values=my-portfolio-ami-pipeline-image-*" --query "Images | sort_by(@, &CreationDate)[-1].ImageId" --output text)
          echo "LATEST_AMI=$LATEST_AMI"
          if [ -z "$LATEST_AMI" ] || [ "$LATEST_AMI" = "None" ]; then
            echo "No previous AMI found, using default AMI."
            LATEST_AMI="ami-057660df437592ff2"  # Fallback to a known good AMI if no previous one exists
          fi
          echo "LATEST_AMI=$LATEST_AMI" >> $GITHUB_ENV

      # Initialize Packer (install plugins)
      - name: Initialize Packer
        run: packer init pipeline/packer-template.pkr.hcl

      # Validate the Packer template
      - name: Validate Packer Template
        run: packer validate -var "source_ami=ami-057660df437592ff2" -var "template_dir=$PWD" pipeline/packer-template.pkr.hcl

      # Build the AMI with Packer
      - name: Build AMI with Packer
        env:
          PACKER_LOG: 1  # Enable detailed Packer logging
        run: |
          packer build -var "source_ami=${{ env.LATEST_AMI }}" -var "template_dir=$PWD" pipeline/packer-template.pkr.hcl
