name: Build AMI on Push

on:
  push:
    branches:
      - main

jobs:
  build_ami:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Packer
      - name: Install Packer
        run: |
          curl -O https://releases.hashicorp.com/packer/1.7.0/packer_1.7.0_linux_amd64.zip
          unzip packer_1.7.0_linux_amd64.zip
          sudo mv packer /usr/local/bin/

      # Install AWS CLI
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      # Set up AWS credentials using GitHub Secrets
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Get latest AMI ID or fallback to default AMI
      - name: Get Latest AMI ID
        id: get_ami
        run: |
          LATEST_AMI=$(aws ec2 describe-images --owners self --filters "Name=name,Values=my-portfolio-ami-pipeline-image-*" --query "Images | sort_by(@, &CreationDate)[-1].ImageId" --output text)
          echo "LATEST_AMI=$LATEST_AMI"
          if [ -z "$LATEST_AMI" ]; then
            echo "No previous AMI found, using default AMI."
            LATEST_AMI="ami-057660df437592ff2"  # Fallback to a known good AMI if no previous one exists
          fi
          echo "LATEST_AMI=$LATEST_AMI" >> $GITHUB_ENV

      # Validate the Packer template with default source_ami
      - name: Validate Packer Template
        run: packer validate -var "source_ami=ami-057660df437592ff2" pipeline/packer-template.json

      # Build the AMI with Packer using dynamic LATEST_AMI
      - name: Build AMI with Packer
        run: |
          packer build -var "source_ami=${{ env.LATEST_AMI }}" -var "template_dir=$PWD" pipeline/packer-template.json
